server:
  port: 9001
  context-path: /resource

security:
  oauth2:
    client:
          client-id: foo
          client-secret: foosecret
          authorized-grant-types: authorization_code,refresh_token,password,implicit
    resource:
      token-info-uri: http://localhost:9000/authserver/oauth/check_token
#      user-info-uri: http://localhost:9000/authserver/user
#      prefer-token-info: true

#数据库配置信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.60.121:3306/liujinlong?autoReconnect=true&userSSL=false
    username: root
    password: 123qwe!@#QWE
    initialize: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
